"""CSS @font-face generator and invariant validator."""

from __future__ import annotations

import re
from typing import Sequence

from cns_webfont.slicing import PhysicalShardPlan


class CSSInvariantError(Exception):
    """Raised when CSS coverage or disjointness invariants are violated."""


def generate_font_face_rule(
    family_name: str,
    woff2_filename: str,
    unicode_range: str,
    rel_woff2_dir: str = "./woff2",
    font_weight: int = 400,
    font_style: str = "normal",
    font_display: str = "swap",
) -> str:
    """Generate a single @font-face CSS rule for a WOFF2 shard."""
    woff2_path = f"{rel_woff2_dir.rstrip('/')}/{woff2_filename}"
    return (
        f"@font-face {{\n"
        f'  font-family: "{family_name}";\n'
        f"  font-style: {font_style};\n"
        f"  font-weight: {font_weight};\n"
        f"  font-display: {font_display};\n"
        f'  src: url("{woff2_path}") format("woff2");\n'
        f"  unicode-range: {unicode_range};\n"
        f"}}"
    )


def generate_css(
    family_name: str,
    shards: Sequence[PhysicalShardPlan],
    rel_woff2_dir: str = "./woff2",
    font_weight: int = 400,
    font_style: str = "normal",
    font_display: str = "swap",
) -> str:
    """Generate complete CSS stylesheet defining all @font-face rules.

    The ordering of shards matches the slicing strategy (Google reverse priority order,
    followed by codepoint-sorted tail bins).

    Args:
        family_name: CSS font-family name (e.g. "TW-Sung" or "TW-Kai").
        shards: Sequence of PhysicalShardPlan objects.
        rel_woff2_dir: Relative directory where WOFF2 files reside from the CSS file.
        font_weight: CSS font-weight.
        font_style: CSS font-style.
        font_display: CSS font-display (default 'swap').

    Returns:
        Formatted CSS content as a string.
    """
    header = (
        f"/*\n"
        f" * CNS11643 Web Font - {family_name}\n"
        f" * Generated by cns-webfont\n"
        f" * License: SIL Open Font License 1.1\n"
        f" */\n\n"
    )

    rules = [
        generate_font_face_rule(
            family_name=family_name,
            woff2_filename=shard.filename,
            unicode_range=shard.unicode_ranges,
            rel_woff2_dir=rel_woff2_dir,
            font_weight=font_weight,
            font_style=font_style,
            font_display=font_display,
        )
        for shard in shards
    ]

    return header + "\n\n".join(rules) + "\n"


def parse_unicode_range_to_codepoints(range_str: str) -> set[int]:
    """Parse CSS unicode-range property string into a set of integer codepoints."""
    codepoints: set[int] = set()
    tokens = [t.strip() for t in range_str.split(",") if t.strip()]

    for token in tokens:
        if not token.upper().startswith("U+"):
            raise CSSInvariantError(f"Invalid unicode-range token: '{token}'")

        token_body = token[2:]
        if "-" in token_body:
            start_str, end_str = token_body.split("-", 1)
            start_cp = int(start_str, 16)
            end_cp = int(end_str, 16)
            if start_cp > end_cp:
                raise CSSInvariantError(f"Invalid range with start > end: '{token}'")
            codepoints.update(range(start_cp, end_cp + 1))
        elif "?" in token_body:
            # Handle wildcard range e.g. U+4E??
            prefix = token_body.replace("?", "")
            q_count = token_body.count("?")
            start_cp = int(prefix + ("0" * q_count), 16)
            end_cp = int(prefix + ("F" * q_count), 16)
            codepoints.update(range(start_cp, end_cp + 1))
        else:
            codepoints.add(int(token_body, 16))

    return codepoints


def verify_css_invariants(css_content: str, expected_codepoints: set[int]) -> None:
    """Verify that CSS @font-face rules satisfy coverage and disjointness invariants.

    Invariants:
    1. union(all CSS unicode-ranges) == expected_codepoints (zero missing, zero extra).
    2. intersection(shard A, shard B) == empty for all distinct shards.

    Raises:
        CSSInvariantError: If any invariant is violated.
    """
    range_matches = re.findall(r"unicode-range:\s*([^;]+);", css_content)
    if not range_matches:
        raise CSSInvariantError("No unicode-range declarations found in CSS content")

    seen_cps: set[int] = set()
    total_range_codepoints = 0

    for idx, range_str in enumerate(range_matches, start=1):
        cps = parse_unicode_range_to_codepoints(range_str)
        if not cps:
            raise CSSInvariantError(f"Shard rule {idx} defines an empty unicode-range")

        overlap = seen_cps & cps
        if overlap:
            sample = [f"U+{cp:04X}" for cp in sorted(overlap)[:5]]
            raise CSSInvariantError(
                f"Shard rule {idx} overlaps with prior shards on "
                f"{len(overlap)} codepoints (sample: {sample})"
            )

        seen_cps.update(cps)
        total_range_codepoints += len(cps)

    # Coverage check
    missing = expected_codepoints - seen_cps
    extra = seen_cps - expected_codepoints

    if missing:
        sample = [f"U+{cp:04X}" for cp in sorted(missing)[:5]]
        raise CSSInvariantError(
            f"CSS coverage invariant violated: {len(missing)} expected codepoints "
            f"missing from CSS (sample: {sample})"
        )

    if extra:
        sample = [f"U+{cp:04X}" for cp in sorted(extra)[:5]]
        raise CSSInvariantError(
            f"CSS coverage invariant violated: {len(extra)} unexpected codepoints "
            f"present in CSS (sample: {sample})"
        )
